<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Authors>SafeStbTrueTypeSharpTeam</Authors>
    <Product>SafeStbTrueTypeSharp</Product>
    <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
    <Description>Safe C# port of stb_truetype.h</Description>
    <PackageLicense>https://wiki.creativecommons.org/wiki/public_domain</PackageLicense>
    <PackageProjectUrl>https://github.com/jeske/SafeStbTrueTypeSharp</PackageProjectUrl>
    <RootNamespace>StbTrueTypeSharp</RootNamespace>
    <Version>1.24.1</Version>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>